### ISSUE TITLE
Add cache locking

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#103]
When consulting the cache, it will often be the case that multiple requests will be handled between when a cache entry expires and when it can be refreshed. This is true for both the memory cache and redis cache. This can create a stampede of re-generating the same content when a cache entry fails, as many workers concurrently update the cached item.

To avoid this problem, cache entries should become locked when they are being regenerated. Clients that encounter a locked cache entry should either serve stale content, an empty request, or wait until the lock has been removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1209)

**Comment by jrconlin** [comment]
Research notes:
Distributed locking via redis:
https://crates.io/crates/redlock
https://redis.io/topics/distlock
* possible, but potentially problematic since there's some discussion about how lock clocks are used.

Option 2: 
https://zookeeper.apache.org/doc/current/index.html
configuration and coordination
(perhaps may be a settings manager system as well?)

**Comment by mythmon** [comment]
Redlock and Distlock are primarily focused on Redis's clustering mode, which we won't need to deal with.  Zookeeper is additionally a multi-server leader election service. It's not meant to be fast. I think both of these routes are overkill for what we need.

Instead we can simply keep a second boolean entry for every key in the cache, that we can use as a simple lock. Since we are only using a single Redis server, there is no synchronization issue.

**Comment by jrconlin** [comment]
Agreed.

The prior comment might be a bit more spill over from https://github.com/mozilla-services/contile/issues/267.
